### PR TITLE
Port to Polymer 1.x

### PR DESCRIPTION
**Pull request by bergie**
Refs noflo/noflo-ui#537

### CODE REVIEW

**Comment by jonnor** [comment]
@bergie whats the status? Mostly working or not? Any limitations, or blockers?

**Comment by bergie** [comment]
@jonnor working fully. Tests passing on both Chrome and PhantomJS

**Comment by jonnor** [comment]
Ok. If we're gonna merge this, then this means bumping major version, since incompatible with old Polymer. Maybe go 1.x to match?

**Comment by bergie** [comment]
In this case the component migration to 1.x was simply done with https://github.com/PolymerLabs/polyup

The only manual tweak was to change the `notify` setting to prevent unwanted events from firing https://github.com/noflo/noflo-polymer/pull/16/commits/6364a67873fd4ac3f29fa455828e04667e7515ce

**Comment by bergie** [comment]
@jonnor yes, major bump sounds reasonable

**Pull request merged**
